version: '3'

services:
  frontend:
    build:
      context: ./frontend
    image: 'gerenciamento-bens-frontend:latest'
    container_name: gerenciamento-bens-frontend
    ports:
      - '3000:80'

  backend:
    image: 'gerenciamento-bens:latest'
    build:
      context: .
      dockerfile: ./src/main/docker/Dockerfile
    container_name: gerenciamento-bens
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres
      - SPRING_DATASOURCE_USERNAME=gerenciamento-postgres
      - SPRING_DATASOURCE_PASSWORD=gerenciamento-postgres
      - AWS_S3_BUCKET-NAME=gerenciamento-bens
      - AWS_S3_URL=http://minio:9000
      - AWS_S3_IS-MINIO=true
      - AWS_S3_ACCESS-KEY=gerenciamento-minio
      - AWS_S3_SECRET-KEY=gerenciamento-minio
      - AWS_DYNAMODB_TABLE-NAME=Validation
      - AWS_DYNAMODB_IS-LOCAL=true
      - AWS_DYNAMODB_URL=http://dynamo:8000/
    depends_on:
      - postgres_db
      - minio
      - minio_bucket
      - dynamo
    ports:
      - '8080:8080'

  postgres_db:
    image: 'postgres:15.0-alpine'
    container_name: postgres
    environment:
      - POSTGRES_USER=gerenciamento-postgres
      - POSTGRES_PASSWORD=gerenciamento-postgres
    ports:
      - "5432:5432"
  pgadmin:
    image: 'dpage/pgadmin4'
    container_name: pgadmin-container
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.com
      - PGADMIN_DEFAULT_PASSWORD=SuperSecret
    ports:
      - "2345:80"

  minio:
    image: 'minio/minio'
    ports:
      - "9001:9001"
      - "9000:9000"
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ACCESS_KEY: gerenciamento-minio
      MINIO_SECRET_KEY: gerenciamento-minio
    command: server --console-address ":9001" /data

  minio_bucket:
    image: 'minio-create-bucket:latest'
    build:
      context: create-bucket
      dockerfile: ./create-bucket.dockerfile
    depends_on:
      - minio
    environment:
      MINIO_ADDRESS: 'minio:9000'
      MINIO_ACCESS_KEY: gerenciamento-minio
      MINIO_SECRET_KEY: gerenciamento-minio
      MINIO_BUCKET_NAME: "gerenciamento-bens"

  dynamo:
    image: amazon/dynamodb-local
    container_name: dynamo
    user: root
    ports:
      - "8000:8000"
    volumes:
      - ./dynamo-local:/home/dynamodb/data
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodb/data"


volumes:
  minio_storage: {}
