version: '3'

services:
  backend:
    image: 'gerenciamento-bens:latest'
    build:
      context: ../../../.
      dockerfile: ./src/main/docker/Dockerfile
    container_name: gerenciamento-bens
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres
      - SPRING_DATASOURCE_USERNAME=gerenciamento-postgres
      - SPRING_DATASOURCE_PASSWORD=gerenciamento-postgres
    depends_on:
      - postgres_db
      - min_io
      - dynamo_db
    ports:
      - '8080:8080'

  postgres_db:
    image: 'postgres:15.0-alpine'
    container_name: postgres
    environment:
      - POSTGRES_USER=gerenciamento-postgres
      - POSTGRES_PASSWORD=gerenciamento-postgres
    ports:
      - "5432:5432"

  min_io:
    image: 'minio/minio'
    ports:
      - "9001:9001"
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: gerenciamento-minio
      MINIO_ROOT_PASSWORD: gerenciamento-minio
    command: server --console-address ":9001" /data

  dynamo_db:
    image: amazon/dynamodb-local
    container_name: dynamo_db
    ports:
      - "8000:8000"
    volumes:
      - ./dynamo-db-local:/home/dynamodb/data
    command: "-jar DynamoDBLocal.jar -sharedDb - dbPath /home/dynamodb/data"

volumes:
  minio_storage: {}
